#vick start vick-init.yaml name
#vick start command deploys the VICK controlplance in the vick namespace
---
#Create VICK namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cellery-system
  labels:
    creator: vick-init
---
#Create service account for the pub-store deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vicksvc-account
  namespace: cellery-system
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pub-store-volume-claim
#  namespace: cellery-system
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: ""
#  selector:
#    matchLabels:
#      purpose: apim-shared-deployment
#---
