apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pub-store-volume-claim
  namespace: cellery-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: apim-shared-deployment
